# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('users', '0002_auto_20191120_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'new'), ('1', 'not paid'), ('2', 'paid'), ('3', 'transport'), ('4', 'closed')], default='0', max_length=2)),
                ('remark', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to='users.DeliveryAddress')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='goods.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_of', to='users.UserInfo')),
            ],
        ),
    ]
